id: QmQZoixjhFwC9oiXdjmKagpTV3bnoa9i6hEsDwQ1eSWu6w
description: Function call to get messages for the database..
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /messages
domains:
    - GeneratedDomain
includes:
    - /functions/Get_Messages.go
execution:
    timeout: 10s
    memory: 10GB
    call: getMessages
